### ISSUE TITLE
Add metadata for all indicators.

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Data#2]
We need to populate the site with metadata for all 74 indicators.

Use [prose](http://prose.io/) to fill out a metadata template for indicators B1 onwards based on the info provided in [the most recent update](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/923203/25-yep-indicators-2020.pdf.pdf). The metadata template was developed for SDG indicators so some of the fields might not be relevant.

**Comment by brockfanning** [comment]
@EFT-Defra Just a note that you can adjust the [_prose.yml file](https://github.com/Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Data/blob/develop/_prose.yml) to remove particular fields that aren't relevant.

**Comment by JamesKeny0n** [comment]
[OIF metadata.docx](https://github.com/Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Data/files/6100324/OIF.metadata.docx)
